---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/tsokbjte/itfinancialmanagementsoftware.com/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R Images $DEPLOYPATH