<?php include 'components/header.php'; ?>
<?php include 'components/nav.php'; ?>
<?php include 'components/hero.php'; ?>
<?php include 'components/what-is-itfm.php'; ?>
<?php include 'components/capabilities.php'; ?>
<?php include 'components/audience.php'; ?>
<?php include 'components/magicorange.php'; ?>
<?php include 'components/simple-idea.php'; ?>
<?php include 'components/footer.php'; ?>